---
- name: "Install pgsql"
  yum:
    name: "{{ items }}"
    state: present
  vars:
    items:
      - postgresql
      - postgresql-server

- name: "Install Psycopg2 dependecies"
  yum:
    name: "{{ items }}"
    state: present
  vars:
    items:
      - gcc
      - python3-devel
      - postgresql-libs
      - postgresql-devel
  
- name: "Install Psycopg2"
  pip: 
    name: psycopg2-binary
    state: present

- name: "Check PostgreSQL is initialized"
  ansible.builtin.stat:
    path: "/var/lib/pgsql/data/pg_hba.conf"
  register: postgres_data

- name: "Initialize PostgreSQL"
  shell: "postgresql-setup initdb"
  when: not postgres_data.stat.exists

- name: "Start postgresql"
  ansible.builtin.systemd:
    daemon_reload: yes
    state: started
    enabled: yes
    name: postgresql

...