---
- name: "Start Container"
  community.docker.docker_container:
    name: php-fpm-container
    image: php-fpm-img
    env:
      POSTGRES_HOST: "{{ ansible_facts.docker0.ipv4.address | string }}"
      POSTGRES_DB: "{{ db_pass | string}}"
      POSTGRES_USER: "{{ db_user | string}}"
      POSTGRES_PASSWORD: "{{ db_pass | string}}"
    state: started
    recreate: yes
    restart: yes
    container_default_behavior: no_defaults
    published_ports:
      - 9000:9000
    volumes:
      - "{{ work_dir }}:/var/www/sre"
  tags: 
    - sre-container
    - sre-container-restart
...