---
- name: "Copy NGINX Configs"
  become: True
  become_user: root

  block: 
    - name: "Copy NGINX APP Config"
      copy:
        src: "files/nginx-app-defaults"
        dest: "/etc/nginx/app-defaults"
      notify:
        restart nginx

    - name: "Copy NGINX HTTP"
      template:
        src: "templates/nginx-default.conf.j2"
        dest: "/etc/nginx/conf.d/default.conf"
      notify:
        restart nginx

    - name: "Copy NGINX config HTTPS"
      template:
        src: "templates/https.conf.j2"
        dest: "/etc/nginx/conf.d/{{ https_server_name }}.conf"
      notify:
        restart nginx

...