---
- name: "Test Docker - pull images"
  docker_image:
    name: "{{ default_container_image }}"
    source: pull
  become: false
  when: test_docker

- name: "Test docker - Create default containers"
  docker_container:
    name: "docker-test-{{ item }}"
    image: "{{ default_container_image }}"
    state: present
    container_default_behavior: no_defaults
  with_sequence: count=5
  become: false
  when: test_docker
...